name: publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -U pip wheel setuptools twine

      - name: Update version
        run: sed -ie "s/version=[^,]*,/version='${GITHUB_REF##*/}',/" setup.py

      - run: cat setup.py

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
